import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  tech: [{type: 'autogenerated', dirName: 'tech'}],
  tools: [{type: 'autogenerated', dirName: 'tools'}],
}

module.exports = sidebars
